
 %==============================================================================================%
 

 includegraphics[width=0.9linewidth]{Rlogo}

 

 Source: R project website (http://www.r-project.org)
 



textbf{Secton 1 - A few basics} 

*  [1.1] Installing ***R***      
*  [1.2] Command Line Interface     
*  [1.3] The Assignment operator     
*  [1.4] Commenting      
*  [1.5] Defining Variables     
*  [1.6] Help Functions      
*  [1.7] The texttt{help.start()} command     
*  [1.8] Basic Maths Operations     
*  [1.9] Basic ***R*** Editor      
 
 
### {1.1 Installing R}
 
*  ***R*** is very easily installed by downloading it from the CRAN website. Installation usually takes
 about 2 minutes. 
*  When installation of R is complete, the distinctive ***R*** icon will appear on your
 desktop. To start ***R***, simply click this Icon. 
*  It is common to re-install ***R*** once a year or so. The
 current version of ***R***, version 3.1.2 was released quite recently.
 
 
 

 
### {1.9 Basic ***R*** Editor}
 
*  ***R*** has an inbuilt script editor. We will use it for this class, but there are plenty of top quality
 Integrated Development Environments out there. (Read up about textbf{RStudio} for example).
*  For a while, we will use the in-built script editor. Although it is advisable to start using textbf{Rstudio} or something similar in the not-too-distant future.
 
 
 
 
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Rscript}         
 end{figure}
    
 %==============================================================================================%
 
### {1.9 Basic ***R*** Editor}
 
*  To start a new script, or open an existing script simply go to File and click the appropriate
 options. A new dialogue box will appear. 
 
*  You can write and edit code using this editor.
*  To pass the code for compiling , press the run line or selection option (The third icon
 on the menu).
 
 
 %==============================================================================================%
 
 
 
*  Another way to read code is to use the texttt{edit()} function, which operates directly from the
 command line. 
*  To see how the code defining an object X was written (or more importantly,
 could have been written) simply type texttt{edit(X)}. 
*  This command has some useful applications
 that we will see later on (the texttt{scan()} command).
 
 
 
### {Script Files}
 
*  Scripts are saved as texttt{.R} files. 
*  These scripts can be called directly using the texttt{source()} command.
 
 
 <pre>
 texttt{source(myScript.R)}
 
 texttt{source(myDatasets.R)}
 
 texttt{source(myFunctions.R)}
 </pre>
<p>
 
 
 
 
 %==============================================================================================%
 
### {1.10 Built-In Data Sets}
 textbf{Inbuilt Data Sets}
 Several data sets , intended as learning tools, are automatically installed when R is installed.
 Many more are installed within packages to complement learning to use those packages. 
 bigskip
 
 textbf{iris} One
 of these is the famous Iris data set, which is used in many data mining exercises.
 
 
*  airquality  ( very useful )
*  mtcars
*  Nile
 
 More are available once packages are loaded.
 
 
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Rdatasets}        
 end{figure}
    
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/RdatasetsMore}   
 end{figure}
    
 %==============================================================================================%
 
 
 
*  To see what data sets are available, simply type texttt{data()}.
 *  To load a data set, simply type in the
 name of the data set. Some data sets are very large.
 *  To just see the first few (or last) rows, we
 use the texttt{head()} function or alternatively the texttt{tail()} function. 
*  The default number of rows of
 these commands is 6. Other numbers can be specified.
 
 
 
 %==============================================================================================%
 
 
*  In many situations, it is useful to call a particular data set using the texttt{attach()} command. This
 will save having to specify the data sets over repeated operations. 
*  The file can then be detached
 using the texttt{detach()} command.
 
 
 
 
 ## {1.19 Saving and Loading R Data Objects}
 In situations where a good deal of processing must be used on a raw dataset in order to prepare
 it for analysis, it may be prudent to save the R objects you create in their internal binary form.
 One attractive feature of this scheme is that the objects created can be read by R programs
 running on different computer architectures than the one on which they were created, making it
 very easy to move your data between different computers. Each time an R session is completed,
 you are prompted to save the workspace image, which is a binary file called .RData in the
 working directory.
 
 %==============================================================================================%
 
 Whenever R encounters such a file in the working directory at the beginning of a session,
 it automatically loads it making all your saved objects available again. So one method for
 
 saving your work is to always save your workspace image at the end of an R session. If you
 would like to save your workspace image at some other time during your R session, you can use
 the save.image() function, which, when called with no arguments, will also save the current
 workspace to a file called .RData in the working directory.
 
 
 %============================================================================= %
 
### {Introduction to R (Continued) }
 
*  [2.1] Three particularly useful commands    
*  [2.2] Changing GUI options     
*  [2.3] Colours      
*  [2.4] Use of the Semi-Colon Operator     
*  [2.5] The texttt{apropos()} Function     
*  [2.6] History       
*  [2.7] The texttt{sessionInfo()} Function     
*  [2.8] Time and date functions     
*  [2.9] Logical States      
*  [2.10] Missing Data      
*  [2.11] Files in the Working Directory     
 
 
 
 %==============================================================================================%
 
 %    2 Introduction to R (Continued)
### {2.1 Some particularly useful commands}
 
 
 The Holy Trinity
 
*  texttt{help()}
*  texttt{summary()}
*  texttt{help.start()}
*  texttt{apropos()}
 
 
 
 %==============================================================================================%
 
### {2.2 Changing GUI options}
 
*  We can change the GUI options using the GUI preferences option on the Edit menu.
 *  (Important
 when teaching R) 
*  A demonstration will be done in class.
 
 
 
 %==============================================================================================%
 
### {2.3 Colours}
 
*  R supported a massive number of colours.
*  Type in colours() (or colors()) to see what colours
 are supported.
 
 
 
 
  %==============================================================================================%
 
### {2.4 Use of the Semi-Colon Operator}
 
*  The semi-colon operator at the end of each line of code is not necessary in general, but using it
 overcomes errors due to copying and pasting from document soft copies. 
*  It is also useful for compacting multiple short statements onto a single line.
*  In other programming
 languages, such as Octave, using the semicolon in this way has a distinct purpose.
 
 
 %==============================================================================================%
 
### {2.5 The texttt{apropos()} Function}
 
*  This function is very useful for determining what functions are available for a particular topic,
 although the process requires a great deal of trial and error. 
*  Suppose we are looking for a
 command to print out the session information. 
*  We would use a very short string (e.g. textbf{essio})
 that would plausibly be part of useful function names.
 
 
 
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Rapropos1}       
 end{figure}
    
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Rapropos2}       
 end{figure}
    
 %==============================================================================================%
 
### {2.6 History}
 
*  The command texttt{history()} is used to obtain the last 25 commands used by ***R***.
*  25 is the default number, you can specify another number.
 
 
 
 
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Rhistory}        
 end{figure}
    
 %==============================================================================================%
 
### {2.7 The texttt{sessionInfo()} Function}
 To get a description of the version of R and its attached packages used in the current session,
 we can use the texttt{sessionInfo()} function
 
 
 
 
 
### {2.7 The texttt{sessionInfo()} Function}
 begin{figure}
 centering
 includegraphics[width=0.99linewidth]{images/sessionInfo}
 %caption{}
 %label{fig:sessionInfo}
 end{figure}
 
 %==============================================================================================%
 
### {2.8 Time and date functions}
 
*  The commands texttt{Sys.time()} and texttt{Sys.Date()} returns the system’s idea of the current date
 with and without time. 
*  We can perform some simple algebraic calculations to compute time
 differences (i.e. to find out how long some code took to compile).
 
 
 
 %==============================================================================================%
 
### {System Time}
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Systime}
 %caption{}
 %label{fig:Systime}
 end{figure}
 
 
 %==============================================================================================%
  
### {2.9 Logical States}
 
*  Logical states TRUE and FALSE are simply specified as such, all in capital letters. 
*  The
 shortcuts T and F are also recognized
 
 
 %==============================================================================================%
 
### {2.10 Missing Data}
 
*  In some cases the entire contents of a vector may not be known. For example, missing data
 from a particular data set.*  A place can be reserved for this by assigning it the special value
 NA.
 NA is a logical constant of length 1 which contains a missing value indicator.
 *  NA stands
 for Not Available.
*  Missing values can adversely affect calculations. Add texttt{na.rm=T} to commands
 
 <pre>
 texttt{mean(X,na.rm=T)}
 </pre>
<p>
 
 
 %==============================================================================================%
 
 
### {2.11 Files in the Working Directory}
 It is possibel to call an R script from the working directory, using the texttt{source()} function.
 <pre>
 
 texttt{source("myfunctions.r")
 source("mydata.r")}
 
 </pre>
<p> 
 We can also send code put directly to a file in the working directory, using the texttt{sink()}
 command. The first time the command is used, the name of the created file is specified.
 Subsequent commands print output directly to this file, until the command is used again to
 cease the operation.
 
 %==============================================================================================%
 
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/sinkiris}
 %caption{}
 %label{fig:sinkiris}
 end{figure}
 
 

 %==============================================================================================%
 
