
<p>
### {Basic R editing – Script Editor and texttt{edit()}}
R has an inbuilt script editor. We will use it for this class, but there are plenty of top quality “Integrated Development Environments “ out there. (Read up about RStudio for  example.)

To start a new script, or open an existing script simply go to “File” on the menu bar and click the appropriate options.
A new dialogue box will appear. You can write and edit code using this editor.
To pass the code for compiling – press the “run line or selection” option (The third icon on the menu).
Another way to edit code is to use the texttt{edit()} function – which operates directly from the command line.  To edit the code defining an object X, simply type edit(X).
%------------------------------------------------------%
<p>
### {Changing GUI options}
We can change the GUI options using the “GUI preferences” option on the Edit menu. (Important when teaching R)
A demonstration will be done in class. 
%------------------------------------------------------%
<p>
### {Embedded Datasets}
Several data sets – intended as learning tools – are automatically installed when texttt{R} is installed. Many more are installed within packages to complement learning to use those packages.  One of these is the famous ``textit{iris}" data set, which is used in many data mining exercises.

         * To see what data sets are available – type texttt{data()}.
         * To load a data set, simply type in the name of the data set. 
         * To specify that a specific data set is to be used for analysis, use the command texttt{attach()}.



Some data sets are very large. To just see the first few rows, we use the head() function.

<pre>
<code>
> head(iris)
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa
</code>
</pre>
<p>
%---------------------------------------------------------------------------------------------%
<p>
####        * {Dimensions of a data set}
We have remarked that some data sets are very large. This is perhaps a good place to consider summary information about data objects.
For a simple vector – a useful command to determine the length (remark: sample size) is the function texttt{length()}.
<pre>
<code>
> Y=5:9
> length(Y)
[1] 5
</code>
</pre>
<p>
%---------------------------------------------------------------------------------------------%
For more complex data sets (and data frames, which we will see later) – we have several tools for assessing the size of data.
<pre>
<code>
> dim(iris)  # dimensions of data set
[1] 150   5
> nrow(iris) # number of rows
[1] 150
> ncol(iris) # number of columns
[1] 5
</code>
</pre>
<p>
%---------------------------------------------------------------------------------------------%
We can also determine the row names and column names using the functions texttt{rownames()} and texttt{colnames()}.
If there are no specific row or column names – the command will just return the indices.

<pre>
<code>
> colnames(iris)
[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

</code>
</pre>
<p>
The command texttt{summary()} is one of the most useful commands in R. It is a generic function used to produce result summaries of the results of various functions. The function invokes particular methods which depend on the class of the first argument. 
In other words – texttt{R} picks out the most suitable type of summary for that data.
{
	small
<pre>
<code>
> summary(iris)
  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width          Species  
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100   setosa    :50  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300   versicolor:50  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300   virginica :50  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199                  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800                  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500                  
>
</code>
</pre>
<p>
}
