


%---------------------------------------------------------------------------------------------%
texttt{summary()} is particularly useful for manipulating data from more complex data objects.
Working directories
You can change your working directly by using the appropriate options on the File menu.
To determine the current working directory – you can use the texttt{getwd()} command:	
<pre>
<code>
> getwd()
[1] "C:/Users/Kevin/Documents"
</code>
</pre>
<p>
To change the working directory – we would use the texttt{setwd()} command.
<pre>
<code>
> getwd()
[1] "C:/Users/Kevin"
>
> setwd("C:/Users/Kevin/Documents")
>
> getwd()
[1] "C:/Users/Kevin/Documents"
</code>
</pre>
<p>
%---------------------------------------------------------------------------------% 
<p>
### {Time and Date functions}
The commands texttt{Sys.time()} and texttt{Sys.Date()} returns the system's idea of the current date with and without time.
We can perform some simple algebraic calculations to compute time differences (i.e. to find out how long some code took to compile.
<pre>
<code>
> X1=Sys.time()
> #Wait a few seconds
>
> X2=Sys.time()
> X2-X1
Time difference of 8.439614 secs
>
> Sys.Date() 
[1] "2012-09-01"
</code>
</pre>
<p>
%---------------------------------------------------------------------------------------------%
<p>
####        * {Coming unstuck}
If you are having trouble with a piece of code that is currently compiling – all you have to do is press ESC. Just like other computing environments.

<p>
####        * {Listing all         * s in a workspace}
To list all         * s in an texttt{R} environment, we use the texttt{ls()} function. This provides a list of all data objects  accessible.
<pre>
<code>
> ls()
 [1] "a"          "A"          "authors"    "b"          "books"     
 [6] "C"          "D"          "ex1"        "Gerb"       "Lst"       
[11] "m"          "m1"         "op"         "presidents" "r"         
[16] "showSmooth" "sm"         "sm.3RS"     "sm2"        "sm3"       
[21] "Trig"       "Vec1"       "x"          "X"          "x.at"      
[26] "x1"         "x2"         "x3R"        "y"          "Y"         
[31] "y.at"      
</code>
</pre>
<p>
%---------------------------------------------------------------------------------------------%

 
<p>
### {Removing  items}
Sometimes it is desirable to save a subset of your workspace instead of the entire workspace. One option is to use the texttt{rm()} function to remove unwanted objects right before exiting your texttt{R} session; another possibility is to use the save function. 

The save function accepts multiple arguments to specify the objects you wish to save, or, alternatively, a character vector with the names of the objects can be passed to save through the texttt{list=} argument. 

Once the objects to be saved are specified, the only other required option is the texttt{file=option}, specifying the destination of the saved R object. Although there is no requirement to do so, it is common to use a suffix of texttt{.rda} or texttt{.RData} for saved texttt{R} workspace files.

For example, to save the texttt{R} objects x, y, and z to a file called texttt{myData.rda} ,the following statements could be used:

<code>
> save(x,y,z,fil= ‘mydata.rda’)
</code>

<p>
### {Saving and Loading R Data Objects}
In situations where a good deal of processing must be used on a raw dataset in order to prepare it for analysis, it may be prudent to save the texttt{R} objects you create in their internal binary form. 

One attractive feature of this scheme is that the objects created can be read by texttt{R} programs running on different computer architectures than the one on which they were created, making it very easy to move your data between different computers. 

Each time an texttt{R} session is completed, you are prompted to save the workspace image, which is a binary file called texttt{.RData} in the working directory. 

Whenever texttt{R} encounters such a file in the working directory at the beginning of a session, it automatically loads it making all your saved objects available again. 
So one method for saving your work is to always save your workspace image at the end of an R session. If you’d like to save your workspace image at some other time during your R session, you can use the texttt{save.image()} function, which, when called with no arguments, will also save the current workspace to a file called .RData in the working directory.
<p>
### {Quitting the R environment}
As the front page text indicates – all you have to do to quite the workspace is to type in texttt{q()}. You will then be prompted to save your work.
