
### {Section 3 - Inspecting a Data Set }
 
*  [3.1] Dimensions of a data set 
*  [3.2] The texttt{summary()} command   
*  [3.3] Structure of a Data Object 
 
 
 % %============================================================================= %
 %
 %frametitle{Section 4 : Packages}
 %
 %  begin{semiverbatim}
 %  4.1 Packages 
 %  4.2 Using and Installing packages 
 %  4.2.1 Version of R 
 %  end{semiverbatim}
 %
 % 
 %
 %end{document}
 
 
 %==============================================================================================%
 
### {Section 3 Inspecting a Data Set}
 large 
 textbf{Summary of useful commands}
 
*  texttt{dim()} and texttt{length()}
*  texttt{nrow()} and texttt{ncol()}
*  texttt{names()}
*  texttt{summary()}
*  texttt{tail()}
*  texttt{head()}
*  texttt{describe()} (from the textbf{psych} package)
 
 
 %==============================================================================================%
 
 
### {3.1 Dimensions of a data set}
 
*  We have remarked that some data sets are very large. 
*  This is perhaps a good place to consider
 summary information about data objects. 
*  For a simple vector, a useful command to determine
 the length (remark: sample size) is the function texttt{length()}.
 
 <pre>
 texttt{Y=4:18}
 texttt{length(Y)}
 
 </pre>
<p>
 For more complex data sets ( and data frames which we will see later) , we have several
 tools for assessing the size of data.
 
 %==============================================================================================%
 
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/dimsiris}
 %caption{}
 %label{fig:dimsiris}
 end{figure}
 
 
 
 
 %==============================================================================================%
 
### {Column (Variable) names and Row names}
 
*  We can also determine the row names and column names using the functions texttt{rownames()}
 and texttt{colnames()}. 
*  If there are no specific row or column names, the command will just return
 the indices.
 
 begin{figure}
 centering
 includegraphics[width=1.0linewidth]{images/colnamesiris}
 %caption{}
 %label{fig:colnamesiris}
 end{figure}
 
 
 %==============================================================================================%
 
### {3.2 The texttt{summary()} command}
 
*  The command texttt{summary()} is one of the most useful commands in ***R***. 
*  It is a generic function used
 to produce result summaries of the results of various functions. 
*  The function invokes particular
 methods which depend on the class of the first argument. 
*  In other words, ***R*** picks out the most
 suitable type of summary for that data.
 
 
 %==============================================================================================%
 
 
 
 begin{figure}
 centering
 includegraphics[width=0.99linewidth]{images/irissummary}
 
 end{figure}
 texttt{summary()} is particularly useful for manipulating data from more complex data objects.
 
 
 %==============================================================================================%
 
 
### {3.3 Structure of a Data Object}
 large
 The structure, class and storage mode of an object can be determined using the following
 commands. Try out a few.
 
 *  texttt{str()}
 *  texttt{class()}
 *  texttt{mode()}
 
 
 
 
 
 %==============================================================================================%
 
### {Checking and Transforming Types}
 
 
*  The texttt{is} family of commands can check if an object is of a certain type.

*  The texttt{as} family of commands can (often) convert an object to a specified type (in some cases not feasible). 

 
 
 
 %==============================================================================================%
 
### {Checking and Transforming Types}
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/numerictypes}    
 end{figure}
  
 %==============================================================================================%
 
 
### {Checking and Transforming Types}
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/typeconversion} 
 end{figure}
    
 %==============================================================================================%
 
 
 Huge
 [mbox{ Section 4 : Packages } ]
 
 
### {Packages}
 
 
*  A Package in ***R*** is a file containing a collection of objects which have some common purpose.
*  Packages enhance the capabilties and scope for research in a certain field. 
*  For example, the
 package MASS contains objects associated with the Venables and Ripleys ``textit{Modern Applied
 Statistics with S}”. 
 
 
 
 %=================================================================== %
 
 
 
 begin{figure}
 centering
 includegraphics[width=0.97linewidth]{CRAN}
 %caption{Comprehensive R Archive Network}
 
 end{figure}
 
 
 
 
 
 %=================================================================== %
  
### {R Packages}
 
 
*  ``10 R packages I wish I knew about earlier" - Drew Conway (Yhat.com, February 2013)
 bigskip*  ``The HadleyVerse" - Hadley Wickham
 
 
 *  ggplot2, dplyr, reshape, lubridate, stringr
 
 *  With Romain Francois, Dianne Cook and Garret Grolemund.
 
 bigskip
*  Dr Brendan Haplin (UL): lme4 ,TraMineR, Gelman's arm, MASS, foreign. 
 bigskip
*  Shiny - Web Applications with ***R***
 
 
 %=================================================================== %
  
### {R Packages}
 
 
 *  
 Some examples of packages are Actuar, written for actuarial science, and
 QRMlib, which complements the Quantitative Risk Management The command library()
 lists all the available packages. 
 
*  To load a particular package, for example MASS, we would
 write
 <pre>
 texttt{library(MASS)}
 </pre>
<p>
 
 %=================================================================== %
 
 
### {Packages}
 
*  The CRAN package repository features 6107 available packages. 
*  Packages contain
 various functions and data sets for numerous purposes, e.g.
 textbf{textit{ggplot2}} package, textbf{textit{AER}} package, textbf{textit{survival}} package, etc.
*  Some packages are part of the basic installation. Others can be
 downloaded from CRAN.
*  To access all of the functions and data sets in a particular package,
 it must be loaded into the workspace. 
*  For example, to load the
 textbf{textit{ggplot2}} package:
 
 
 <pre>
 texttt{install.packages(ggplot2)}
 
 texttt{library(ggplot2)}
 </pre>
<p>
 
 %==============================================================================================%
 
### {4.2 Using and Installing packages}
 
*  Many packages come with R. To use them in an R session, you need to load the package, as
 previously demonstrated.
*  Some packages are not automatically installed when you install R but they need to be downloaded
 and installed individually. 
*  We must first install them using the install.packages()
 function, which typically downloads the package from CRAN and installs it for use. (follow the
 instructions as indicated).
 
 

 %==============================================================================================%
 
### {4.2.1 Version of R}
 Many packages will require you to have the most recent version of R and also other packages.
 It is a good idea to update regularly.
 
 %==============================================================================================%
 
 [mbox{Section 5 : Data Creation, Data Entry, Data Import and Export}]
 
 %==============================================================================================%
 
### {5.1 The texttt{c()} command}
 To create a simple data set, known as a vector, we use the c() command to create the vector.
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/makevector1}
 %caption{}
 %label{fig:makevector1}
 end{figure}
 
 
 
 %==============================================================================================%
 
### {Vectors}
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/makevectors}
 %caption{}
 %label{fig:makevectors}
 end{figure}
 
 
 %==============================================================================================%
 
### {Vectors} 
 Vectors can be bound together either by row or by column.
 begin{figure}
 centering
 includegraphics[width=1.0linewidth]{images/cbindrbind}
 end{figure}
 
 
 
 %==============================================================================================%
 
 5.3 Using the data editor
 
 
 %==============================================================================================%
 
### {5.4 Spreadsheet Interface}
 ***R*** provides a spreadsheet interface for editing the values of existing data sets. We use the
 command texttt{data.entry()}, and name of the data object as the argument. (Also try out the
 fix() command)
 % <pre>
 % begin{semiverbatim}
 % > data.entry(X) # Edit the data set and exit interface
 % > X
 % end{semiverbatim}
 % </pre>
<p>
 
 
 
 
 
 
 
 end{document}
