
The ``cards()`` command describes each card from a deck of cards. The ``roulette()`` commands describes each possible spin from a roulette wheel.

\subsection{Computing Probabilities}
We can evaluate the probability associated with each sample point using the ``makespace()`` argument.
\begin{verbatim}
> rolldie(1,makespace=TRUE)
  X1     probs
1  1 0.1666667
2  2 0.1666667
3  3 0.1666667
4  4 0.1666667
5  5 0.1666667
6  6 0.1666667
>
> tosscoin(3,makespace=TRUE)
  toss1 toss2 toss3 probs
1     H     H     H 0.125
2     T     H     H 0.125
3     H     T     H 0.125
4     T     T     H 0.125
5     H     H     T 0.125
6     T     H     T 0.125
7     H     T     T 0.125
8     T     T     T 0.125
\end{verbatim}
We can use this to compute the probability of certain events. Suppose we wish to compute the probability of a sum of 28 or more from five dice rolls. Importantly, each column of the output has a name. X1, X2 etc. Lets subset the sample space such that the sum of the 5 X variables is greater than or equal to 28. 
\begin{framed}
\begin{verbatim}
subset(rolldie(5,makespace=TRUE), X1 + X2 + X3 + X4 + X5 >= 28)
X = subset(rolldie(5,makespace=TRUE), X1 + X2 + X3 + X4 + X5 >= 28)
names(X)
X$prob
sum(X$prob)
\end{verbatim}


\begin{verbatim}
> X = subset(rolldie(5,makespace=TRUE), X1 + X2 + X3 + X4 + X5 >= 28)
> names(X)
[1] "X1"    "X2"    "X3"    "X4"    "X5"    "probs"
>
> X$prob
 [1] 0.0001286008 0.0001286008 0.0001286008 0.0001286008
 [5] 0.0001286008 0.0001286008 0.0001286008 0.0001286008
 [9] 0.0001286008 0.0001286008 0.0001286008 0.0001286008
[13] 0.0001286008 0.0001286008 0.0001286008 0.0001286008
[17] 0.0001286008 0.0001286008 0.0001286008 0.0001286008
[21] 0.0001286008
>
>
 sum(X$prob)
[1] 0.002700617
\end{verbatim}

%-----------------------------------------------------------------------------------------------------------------------------------%

### Cards example

Compute the probability of a King or Queen.
\begin{framed}
\begin{verbatim}
S <- cards(,makespace=TRUE)
subset(S, rank %in% c("Q","K"))
\end{verbatim}


\begin{verbatim}
> subset(S, rank %in% c("Q","K"))
   rank    suit      probs
11    Q    Club 0.01923077
12    K    Club 0.01923077
24    Q Diamond 0.01923077
25    K Diamond 0.01923077
37    Q   Heart 0.01923077
38    K   Heart 0.01923077
50    Q   Spade 0.01923077
51    K   Spade 0.01923077
\end{verbatim}

\begin{verbatim}
> X = subset(S, rank %in% c("Q","K"))
> sum(X$probs)
[1] 0.1538462
\end{verbatim}
