
%---------------------------------------------------------------------------------%
### {Relational operators}
A relational operator tests some kind of relation between two
entities. For $R$ the relational operators are as follows:
\begin{center}
\begin{tabular}{|c|c|c|c|}
  \hline

  Equals & == & Less or equal to  & <= \\
  \hline
  Not Equal & != & Greater than & > \\
  \hline
  Less than & < & Greater than & >= \\
  \hline
\end{tabular}
\end{center}

%---------------------------------------------------------------------------------%
### 
{Logical operators}

*  The logical operators are AND, OR and NOT

*  if c1 and c2 are logical expressions, then $c1 \& c2$ is
their intersection (`AND'), $c1 | c2$ is their union (`OR'), and
$!c1$ is the negation of c1.

\begin{center}
\begin{tabular}{|c|c|c|c|}
  \hline
  AND & $ \& $ & also  & $\&\&$ \\
  \hline
  OR & $|$ & also & $||$ \\
  \hline
  NOT & $!$ & &  \\
  \hline
\end{tabular}
\end{center}

%numeric
%
%Creates or coerces objects of type "numeric".
%numeric(length = 0)
%as.numeric(x, ...)
%is.numeric(x)


Relational and Logical Operators
================================================

Relational operators allow for the comparison of values in vectors.
\begin{center}
\begin{tabular}{|c|c|}
  \hline
greater than &	$>$\\
less than&	$<$\\
equal to	&$==$\\
less than or equal to&	$<=$\\
greater than or equal to&	$>=$\\
not equal to	&$!=$\\
  \hline
\end{tabular}
\end{center}
 	\end{frame}
 	\begin{frame}

Note the difference of the equality operator "==" with assignment operator "=".

\& and \&\& indicate logical AND and $\|$ and $\|\|$ indicate logical OR.

The shorter form performs element-wise comparisons in much the same way as arithmetic operators. The longer form is appropriate for programming control-flow and typically preferred in "if" clauses.


\item We can use relational operators to subset vectors (as well as more complex data objects such as data frames, which we will meet later).
\item We specify the  relational condition in square brackets.
\item We can construct compound relational conditions too, using logical operators
\end{itemize}
%----------------------------------%
\begin{framed}
\begin{verbatim}
> vec=1:19
> vec[vec<5]
[1] 1 2 3 4
> vec[(vec<6)|(vec>16)]
[1]  1  2  3  4  5 17 18 19
\end{verbatim}
\end{framed}

