
Large
<p>
#### {Analysis of residuals}

 Perform an analysis of regression residuals ( you can pick the best regression model from last <p>
### ).
 Are the residuals normally distributed?

* Histogram /Boxplot / QQ plot / Shapiro Wilk Test
* Also you can plot the residuals to check that there is constant variance.



<pre>
<code>
y <- rnorm(10)
x <- rnorm(10)
fit1 <- lm(y~x)
res.fit1 <-resid(fit1)
plot(res.fit1)
</code>
</pre>
<p>

<p>
### {Assessing a Linear Regression :Model Diagnostics}

The ease of implementation fosters the impression that linear regression is easy: just use the texttt{textbf{lm()}} function. Yet fitting
this is only the beginning.

After a linear regression analysis has been performed. It is good practice to verify the model’s quality
by running diagnostic checks.

The approach we will take is to create diagnostic plots, by plotting the model object. Rather than producing a scatterplot, this method will produce several diagnostic plots:



<pre>
<code>

Fit1 <- lm(Sepal.length ~ Sepal.Width, data=iris)
plot(Fit1)
</code> 
</pre>
<p>


Next, identify possible outliers either by looking at the diagnostic plot of the residuals
%=================================================================================== %

Another approach is to use the texttt{textbf{outlierTest()}} function of the textit{textbf{car}} package:



<pre>
<code>
#If package not installed, uncomment next line.
#install.packages("car")

library(car)
outlierTest(Fit1)
</code> 
</pre>
<p>
<code>
> outlierTest(Fit1)

No Studentized residuals with Bonferonni p < 0.05
Largest |rstudent|:
rstudent unadjusted p-value Bonferonni p
1322.791550.0059429 0.89143

</code>
%=================================================================================== %

<p>
#### {Influence Measures}

Finally, identify any overly influential observations by using the texttt{textbf{influence.measures()}} 
function.
If an observation is considered influential, it will be indicated with an asterisk on the right hand side. Interpretation of the individual statistics, such as textit{DFFITS} and textit{DFBETA} are beyond the scope of this workshop.



<pre>
<code>
influence.measures(Fit1)
</code> 
</pre>
<p>

end{document}
