
%--------------------------------------------------------Inference Procedures and testing for Normality-%

%chapter{Normality Assumptions and Outliers}
%
#### {Grubbs Test for outliers}
%<p>
#### {Anderson Darling Test}
%<p>
#### {Normal Probability plots}
%
#### { Kolmogorov Smirnov Test}





<p>
#### {Subsetting datasets by rows}

Suppose we wish to divide a data frame into two different <p>
### . The simplest approach we can take is to create two new data sets, each assigned data from the relevant rows of the original data set.

Suppose our dataset ``Info" has the dimensions of 200 rows and 4 columns. We wish to separate "Info" into two subsets , with the first and second 100 rows respectively. ( We call these new subsets "Info.1" and "Info.2".)
<code>
Info.1 = Info[1:100,]		#assigning "info" rows 1 to 100
Info.2 = Info[101:200,]		#assigning "info" rows 101 to 200
</code>

More useful commands such as rbind() and cbind()  can be used to manipulate vectors.

Part 2 Strategies for Data project

Exploratory Data Analysis

The first part of your report should contain some descriptive statistics and summary values. Also include some tests for normality.

      {Regression}
You should have a data set with multiple columns, suitable for regression analysis.
Familiarize yourself with the data, and decide which variable is the dependent variable.

Also determine the independent variables that you will use as part of your analysis.

      {Correlation Analysis}
Compute the Pearson correlation for the dependent variable with the respective independent variables.  As part of your report, mention the confidence interval for the correlation estimate
Choose the independent variables with the highest correlation as your candidate variables.
For these independent variables, perform a series of simple linear regression procedures.
<code>
lm(y~x1)
lm(y~x2)
</code>
Comment on the slope and intercept estimates and their respective p-values. Also comment on the coefficient of determination (multiple R squared). Remember to write the regression equations.
Perform a series of multiple linear regressions, using pairs of candidate independent variables.
<code>
lm(y~x1 +x2)
lm(y~x2 +x3)
</code>
Again, comment on the slope and intercept estimates, and their respective p-values.
In this instance, compare each of the models using the coefficient of determinations. Which model explains the data best?
<p>
#### {Analysis of residuals}
Perform an analysis of regression residuals ( you can pick the best regression model from last <p>
### ).
Are the residuals normally distributed?
	Histogram /  Boxplot / QQ plot / Shapiro Wilk Test
Also you can plot the residuals to check that there is constant variance.
<code>
y=rnorm(10)
x=rnorm(10)
fit1=lm(y~x)
res.fit1 = resid(fit1)
plot(res.fit1)
</code>




<p>
### {Combining plots}
It is possible to combine two plots. We used the graphical parameters command texttt{par()} to create an array. 
Often we just require two plots side by side or above and below. We simply specify the numbers of rows and columns of this array using the texttt{mfrow} argument, passed as a vector.

<code>
par(mfrow=c(1,2))
plot(x,y1)			# draw first plot
plot(x,y2)			# draw second plot
par(mfrow=c(1,1))		# reset to default setting.
</code>

<p>
### {Plot of single vectors}
If only one vector is specified i.e. texttt{plot(x)},  the plot created will simply be a scatter-plot of the values of x against their indices.

$plot(x)$
Suppose we wish to examine a trend that these points represent. We can connect each covariate using a line.

$plot(x, type = "l")$
If we wish to have both lines and points, we would input the following code. This is quite useful if we wish to see how a trend develops over time.
$plot(x, type = "b")$






