
%-----------------------------------------------------------------------------------------------------------------------------------%
\section{Gambler's Fallacy}


The Gambler's fallacy, also known as the Monte Carlo fallacy (because its most famous example happened in a Monte Carlo Casino in 1913),and also referred to as the fallacy of the maturity of chances, is the belief that if deviations from expected behaviour are observed in repeated independent trials of some random process, future deviations in the opposite direction are then more likely. (Wikipedia)
#### {Monte Carlo Casino}

The most famous example of the gambler's fallacy occurred in a game of roulette at the Monte Carlo Casino on August 18, 1913, when the ball fell in black 26 times in a row. This was an extremely uncommon occurrence, although no more nor less common than any of the other 67,108,863 sequences of 26 red or black. Gamblers lost millions of francs betting against black, reasoning incorrectly that the streak was causing an "imbalance" in the randomness of the wheel, and that it had to be followed by a long streak of red. (Wikipedia)
#### {Implementation with \texttt{R}}
Firstly let simulate the outcomes of a Roulette Wheel. For the sake of simplicity, we will disregard "Green" and let ``Black" be signified by an outcome of 1 and ``Red" signified by an outcome of 2.
For this we will use the \texttt{runif()} command, as well as the \texttt{ceiling()} command, which rounds a value up to the next highest integer.

<pre>
<code>
runif(5)
2*runif(5)
ceiling(2*runif(5))
</code>
</pre>
<code>
> runif(5)
[1] 0.02646220 0.90602044 0.45596144 0.25390162 0.06416899
> 
> 
> 2*runif(5)
[1] 1.4458583 0.7452968 0.7861305 0.4930401 1.9711546
> ceiling(2*runif(5))
[1] 2 2 2 1 1
</code>
In this last code segment, we get ``Red" three times in a row, and  then two "Blacks". Try it for a larger number of trials.(e.g. 100)
<pre>
<code>
ceiling(2*runif(1000))
</code>
</pre>
What is of interest is the number of repeated colours. What we could do is to construct a ``For" loop so as to monitor how often a colour repeats. Each time a new colour comes up, the sequence counter gets set to 1. If the next spin results in the same colour, the sequence number is set to 2, if it happens again, the next sequence number is 3, and so on.

Firstly let set up a basic for loop to generate the colours.Ths code is more elaborate than the approach we used already, but it is easy to use this for studying repetitions.


<pre>
<code>
M=100

#First Spin
Colour=ceiling(2*runif(1))

for(i in 2:M)
  {
  # Next Colour
  NextCol =  ceiling(2*runif(1))
  Colour = c(Colour,NextCol)
  }
</code>
</pre>




<pre>
<code>
M=100

#First Spin
Colour=ceiling(2*runif(1))


# Start a vector with a single value of 1.
SeqNo=c(1)  

for(i in 2:M)
  {
  # Next Colour
  NextCol =  ceiling(2*runif(1))
  Colour = c(Colour,NextCol)
  

  #If the current colour is the same as the last, then the current 
  #value in the sequence number vector  is 1 more than the last.
  #
  #Otherwise the current sequence number is reset to 1.
  if (Colour[i] == Colour[i-1])
    {
    SeqNo[i] = SeqNo[i-1]+1
    }else SeqNo[i]=1
  }
</code>
</pre>

<code>
> max(SeqNo)
[1] 5
>
> cbind(Colour,SeqNo)
       Colour SeqNo
  [1,]      2     1
  [2,]      2     2
  [3,]      2     3
  [4,]      1     1
  [5,]      2     1
  [6,]      2     2
  [7,]      1     1
  [8,]      1     2
  [9,]      2     1
 [10,]      1     1
</code>
To reduce data that needs to be collected, we will look at a Sequence Maximum. If there is a change of colour, the last sequenc number is added to a special vector:  SeqMax. For the sake of brevity, Any values lower than 3 in SeqMax will be discarded afterwards.
%---------------------------------%

<pre>
<code>
M=100

#First Spin
Colour=ceiling(2*runif(1))
SeqNo=c(1)

SeqMax=numeric()

for(i in 2:M)
  {
  # Next Colour
  NextCol =  ceiling(2*runif(1))
  Colour = c(Colour,NextCol)


  if (Colour[i] == Colour[i-1])
    {
    SeqNo[i] = SeqNo[i-1]+1
    }else{SeqNo[i]=1;SeqMax=c(SeqMax,SeqNo[i-1])}
}	
SeqMax = SeqMax[SeqMax>3]
</code>
</pre>
Increase the number of iterations to a large number, say 100,000. Then see what turns up in the SeqMax vector. Use the \texttt{table()} command to determine the distribution.
<code>
> table(SeqMax[SeqMax>10])

11 12 13 14 15 18 
21  6  2  3  1  1 
</code>
%-----------------------------------------------------------------------------------------------------------------------------------%

#### {Playing with Dice}

A sequence of integers can be created using the ":" operator, specifying the upper and lower bounds on either side. This is very useful for Dice experiments. Importantly this sequence is constructed as a vector.
<pre>
<code>
Dice = 1:6
</code>
</pre>

Another important command is the \texttt{sample()} command. This command causes \texttt{R} to select $n$ items from the specified vector. We can use it to simulate one roll of a die.
<pre>
<code>
Dice = 1:6
sample(Dice,1)
</code>
</pre>
<code>
> sample(Dice,1)
[1] 2 
> 
> sample(Dice,1)
[1] 4 
>
> sample(Dice,1)
[1] 1
> 
> sample(Dice,1)
[1] 2
</code>

\noindent Suppose we wish to simulate two rolls of a die. Surely we just specify 2 in the argument of the \texttt{sample()} command. In fact we do, but this is not enough.
The \texttt{sample()} command works on the default basis of \textbf{\textit{sampling without replacement}}. That is to say: once a number has been selected, it can not be selected again.
<code>
> sample(Dice,6)
[1] 4 3 6 1 2 5
> sample(Dice,7)
Error in sample(Dice, 7) : 
  cannot take a sample larger than the population when 'replace = FALSE'
</code>
What we do here is to additionally specify \texttt{replace=TRUE}. This specifies an experiment where there is \textbf{\textit{sampling with replacement}}. We can also use the \texttt{table()} function to study the outcomes of the simulation.
<code>
> sample(Dice,20,replace=TRUE)
 [1] 4 1 3 2 5 4 4 4 6 5 6 6 5 6 6 5 1 1 1 3
>
> X= sample(Dice,20,replace=TRUE)
> table(X)
X
1 2 3 4 5 6 
4 4 2 3 3 4 
> mean(X)
[1] 3.45
</code>
Let work on the basis of 100 dice rolls, and for the sake of simplicity let us consider the sum of those 100 rolls. Importantly, we are simulating a \textbf{fair} die. We expect to get a value of approximately 350, but each time we perform the experiment their will slight fluctuations.  Try the last line of the code below a few times. How many times do you get a figure less than 340 or greater than 360?
<pre>
<code>
X= sample(Dice,100,replace=TRUE)
sum(X)

#Equivalently
sum(sample(Dice,100,replace=TRUE))
</code>
</pre>

#### {Simulation Study}
Lets consider this Dice Roll Summation experiment. We will perform the experiment 100000 times, and see what sort of distribution of summations we get.
We will save the results in a vector called \texttt{sums}.
<pre>
<code>
Sums=numeric()    # Initialize An Empty Vector
M=100000  # Number of Iterations

for (i in 1:M)
    {
     NewSum=sum(sample(Dice,100,replace=TRUE))
     Sums = c(Sums, NewSum)
     }
</code>
</pre>

We can perform some basic statistical operations to study this vector. In particular we are interested in the extremes: How many times was there a summation less than 300, and how many times was there a summation greated than 400? (around 1.5\% probability in each case)

<code>
> length(Sums[Sums<300])
[1] 144
> length(Sums[Sums>400])
[1] 160  
</code>

Lets us look at a histogram (a type of bar chart) of the \texttt{Sums} vector ( Use around breaks =100 to specify more intervals). What sort of shape is this histogram?
<pre>
<code>
hist(Sums, breaks=100)
</code>
</pre>

This is a ver crude introduction to the Central Limit Theorem. Even though the Dice Rolls are not normally distributed, the distribution of summations, are described in this experiment, are from a normally distributed sampling population. Also consider the probability of getting a sum more than 400. Recalling that dice simulation is for fair dice, the probability of getting a score more extreme than 400 is 1.5\% approximately. This provides (again crudely) an introduction to the idea of p-values , which are used a lot in statistical inference procedures. 

Suppose it was not certain whether a die was fair or crooked favouring higher values such as 4,5 and 6. The 100 roll experiment was performed and the score turned out to be 400.  It would be a very unusual outcome for a fair die, but not impossible. For crooked dice, larger summations would be expected and a score of approximately 400 would be common. Would you think the die was fair or crooked.

Footnote: Arbitrarily, let us consider a crooked dice, where 4,5 and 6 are twice a likely to appear. Try out the following code.
<code>
CrookedDice=c(1,2,3,4,4,5,5,6,6)
sum(sample(CrookedDice,100,replace=TRUE))
</code>
