is.flashlight Check functions for flashlight Classes

#### Description

Checks if an object inherits specific class relevant for the flashlight package.

#### Usage
<pre><code>

is.flashlight(x)
is.multiflashlight(x)
is.light(x)
is.light_performance(x)
is.light_performance_multi(x)
is.light_importance(x)
is.light_importance_multi(x)
is.light_breakdown(x)
is.light_breakdown_multi(x)
is.light_ice(x)
10 is.flashlight
is.light_ice_multi(x)
is.light_profile(x)
is.light_profile_multi(x)
is.light_effects(x)
is.light_effects_multi(x)
Arguments
x Any object.

#### Value

A logical vector of length one.
Functions
*  is.multiflashlight: Check for multiflashlight object.
*  is.light: Check for light object.
*  is.light_performance: Check for light_performance object.
*  is.light_performance_multi: Check for light_performance_multi object.
*  is.light_importance: Check for light_importance object.
*  is.light_importance_multi: Check for light_importance_multi object.
*  is.light_breakdown: Check for light_breakdown object.
*  is.light_breakdown_multi: Check for light_breakdown_multi object.
*  is.light_ice: Check for light_ice object.
*  is.light_ice_multi: Check for light_ice_multi object.
*  is.light_profile: Check for light_profile object.
*  is.light_profile_multi: Check for light_profile_multi object.
*  is.light_effects: Check for light_effects object.
*  is.light_effects_multi: Check for light_effects_multi object.

#### Examples
```{r}

a <- flashlight(label = "a")
is.flashlight(a)
is.flashlight("a")
```
