
%------------------------------------------------------------------------------------------------%

chapter{Descriptive Statistics}

<p>
### {Basic Statistics}


begin{myindentpar}{1cm}
<code>
> X=c(1,4,5,7,8,9,5,8,9)
> mean(X);median(X)#mean and median of vector
[1] 6.222222
[2] 7
> sd(X)     #standard deviation of Vector
[1] 2.682246
> length(X) #sample size of vector
[1] 9
> sum(X)
[1] 56
> X^2
[1]  1 16 25 49 64 81 25 64 81
> rev(X)
[1] 9 8 5 9 8 7 5 4 1
> sort(X)   #      s in ascending order
[1] 1 4 5 5 7 8 8 9 9
> X[1:5]
[1] 1 4 5 7 8
</code>
end{myindentpar}



<p>
### {Summary Statistics}
The texttt{R} command texttt{summary()} returns a summary statistics for a simple dataset.
The texttt{R} command texttt{fivenum()} returns a summary statistics for a simple dataset, but without the mean.
Also, the quartiles are computed a different way.


begin{myindentpar}{1cm}
<code>
> summary(mtcars$mpg)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  10.40   15.43   19.20   20.09   22.80   33.90 
>
> fivenum(mtcars$mpg)
[1] 10.40 15.35 19.20 22.80 33.90
</code>
end{myindentpar}





<p>
### {Bivariate Data}
 begin{myindentpar}{1cm}
<code>
> Y=mtcars$mpg
> X=mtcars$wt
>
> cor(X,Y)   #Correlation
[1] -0.8676594
>
> cov(X,Y)   #Covariance
[1] -5.116685
</code>
end{myindentpar}


<p>
### {Histograms}
Histograms can be created using the texttt{hist()} command.
To create a histogram of the car weights from the Cars93 data set

begin{myindentpar}{1cm}
<code>
hist(mtcars$mpg, main="Histogram of MPG (Data: MTCARS) ")
</code>
end{myindentpar}
texttt{R} automatically chooses the number and width of the bars. We can
change this by specifying the location of the break points.


<code>hist(Cars93$Weight, breaks=c(1500, 2050, 2300, 2350, 2400,
2500, 3000, 3500, 3570, 4000, 4500), xlab="Weight",
main="Histogram of Weight")
</code>


end{document}

<p>
### {Boxplot}
Boxplots can be used to identify outliers.

By default, the texttt{boxplot()} command sets the orientation as vertical. By adding the argument texttt{horizontal=TRUE}, the orientation can be changed to horizontal.

<pre>
<code>
boxplot(mtcars$mpg, horizontal=TRUE, xlab="Miles Per Gallon",
main="Boxplot of MPG")
</code>
</pre>
<p>

%begin{figure}
%  Requires usepackage{graphicx}
%  includegraphics[scale=0.4]{MTCARSboxplot.png}
%  caption{Boxplot}label{boxplot}
%end{figure}




chapter{Advanced R code}
<p>
### {Data frame}
A Data frame is
<p>
#### {Merging Data frames}

<p>
### {Functions}
Syntax to define functions

<pre>
<code>
 myfct <- function(arg1, arg2, ...) { function_body }
</code>
</pre>
<p>
The value returned by a function is the value of the function body, which is usually an unassigned final expression, e.g.: return()

Syntax to call functions
<pre>
<code>
 myfct(arg1=..., arg2=...)
</code>
</pre>
<p>


<p>
#### {Time and Date}
It is useful . The length of time a program takes is interesting.


<pre>
<code>
date() # returns the current system date and time
</code>
</pre>
<p>


<p>
### {The Apply family}

Sometimes want to apply a function to each element of a
vector/data frame/list/array.

Four members: lapply, sapply, tapply, apply

lapply: takes any structure and gives a list of results (hence
the `l')

sapply: like lapply, but tries to simplify the result to a
vector or matrix if possible (hence the `s')

apply: only used for arrays/matrices

tapply: allows you to create tables (hence the `t') of values
from subgroups defined by one or more factors.


<p>
### {Plots}
This <p>
###  is an introduction for producing simple graphs with
the R Programming Language.

Line Charts  Bar Charts Histograms Pie
Charts Dotcharts




      
      

 <code>
> code here
 </code>


<p>
#### { Charts}

begin{myindentpar}{1cm}
<code>
# Define 2 vectors cars <- c(1, 3, 6, 4, 9) trucks <- c(2, 5, 4,
5, 12)

# Calculate range from 0 to max value of cars and trucks g_range
<- range(0, cars, trucks)

# Graph autos using y axis that ranges from 0 to max # value in
cars or trucks vector.  Turn off axes and # annotations (axis
labels) so we can specify them ourself plot(cars, type="o",
col="blue", ylim=g_range,
   axes=FALSE, ann=FALSE)

# Make x axis using Mon-Fri labels axis(1, at=1:5,
lab=c("Mon","Tue","Wed","Thu","Fri"))

# Make y axis with horizontal labels that display ticks at # every
4 marks. 4     0:g_range[2] is equivalent to c(0,4,8,12). axis(2,
las=1, at=4     0:g_range[2])

# Create box around plot box()

# Graph trucks with red dashed line and square points
lines(trucks, type="o", pch=22, lty=2, col="red")

# Create a title with a red, bold/italic font title(main="Autos",
col.main="red", font.main=4)

# Label the x and y axes with dark green text title(xlab="Days",
col.lab=rgb(0,0.5,0)) title(ylab="Total", col.lab=rgb(0,0.5,0))

# Create a legend at (1, g_range[2]) that is slightly smaller #
(cex) and uses the same line colors and points used by # the
actual plots legend(1, g_range[2], c("cars","trucks"), cex=0.8,
   col=c("blue","red"), pch=21:22, lty=1:2);

</code>
end{myindentpar}
<p>
#### {Bar charts}
begin{myindentpar}{1cm}
<code>
# Define the cars vector with 7 values
cars <- c(1, 3, 6, 4, 9, 5, 7)
# Graph cars
barplot(cars)
</code>
end{myindentpar}
<p>
#### {Boxplots}
<p>
#### {Setting graphical parameters}
<p>
#### {Miscellaneous}
The following code can be used to make variations of the plots.

begin{myindentpar}{1cm}
 <code>
# Make an empty chart
plot(1, 1, xlim=c(1,5.5), ylim=c(0,7), type="n", ann=FALSE)

# Plot digits 0-4 with increasing size and color
text(1:5, rep(6,5), labels=c(0:4), cex=1:5, col=1:5)

# Plot symbols 0-4 with increasing size and color
points(1:5, rep(5,5), cex=1:5, col=1:5, pch=0:4)
text((1:5)+0.4, rep(5,5), cex=0.6, (0:4))

# Plot symbols 5-9 with labels
points(1:5, rep(4,5), cex=2, pch=(5:9))
text((1:5)+0.4, rep(4,5), cex=0.6, (5:9))

# Plot symbols 10-14 with labels
points(1:5, rep(3,5), cex=2, pch=(10:14))
text((1:5)+0.4, rep(3,5), cex=0.6, (10:14))

# Plot symbols 15-19 with labels
points(1:5, rep(2,5), cex=2, pch=(15:19))
text((1:5)+0.4, rep(2,5), cex=0.6, (15:19))

# Plot symbols 20-25 with labels
points((1:6)     0.8+0.2, rep(1,6), cex=2, pch=(20:25))
text((1:6)     0.8+0.5, rep(1,6), cex=0.6, (20:25))
</code>
end{myindentpar}

<p>
#### {Lattice Graphs}
<p>
#### {setting up}
Execute the following command:
begin{myindentpar}{1cm}
<code>
library(lattice)
</code>
end{myindentpar}
For information on lattice, type:
begin{myindentpar}{1cm}
<code>
help(package = lattice)
</code>
end{myindentpar}
The examples in this <p>
###  are generally drawn from the R documentation and Murrell (2006).

Murrell gives three reasons for using Lattice Graphics:

They usually look better.
They can be extended in powerful ways.
The resulting output can be annotated, edited, and saved

<p>
#### {3 Dimensional Graphs}
How to do a 3-d graph


chapter{Statistical Analysis using R}
<p>
### {Confidence Intervals}
<p>
#### {Confidence Intervals for Large Samples}
<p>
#### {Confidence Intervals for Small Samples}

<p>
### {Linear Models}

The Slope and Intercept
begin{myindentpar}{1cm}
<code>

</code>


<p>
### {ANOVA}
